const channels = [
  // National News Channels
  {
    id: "aaj-tak-404p",
    name: "Aaj Tak",
    quality: "404p",
    url: "https://aajtaklive-amd.akamaized.net/hls/live/2014416/aajtak/aajtaklive/live_404p/chunks.m3u8",
    status: "loading",
    isLive: false,
    viewers: "2.4M",
    uptime: "24/7",
    category: "National",
    type: "hls", // hls or embed
  },
  {
    id: "aaj-tak-hd",
    name: "Aaj Tak HD",
    quality: "HD",
    url: "https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8",
    status: "loading",
    isLive: false,
    viewers: "1.8M",
    uptime: "24/7",
    category: "National",
    type: "hls", // hls or embed
  },

  {
    id: "abp-ganga",
    name: "ABP Ganga",
    quality: "1080p",
    url: "https://abplivetv.akamaized.net/hls/live/2043013/ganga/master.m3u8",
    status: "loading",
    isLive: false,
    viewers: "892K",
    uptime: "24/7",
    category: "UP Regional",
    type: "hls", // hls or embed
  },
  {
    id: "dd-news",
    name: "DD News",
    quality: "1080p",
    url: "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/0811cd8c37ca4c409d5385a6cd2fa18b/index.m3u8",
    status: "loading",
    isLive: false,
    viewers: "1.2M",
    uptime: "24/7",
    category: "National",
    type: "hls", // hls or embed
  },
  {
    id: "et-now-swadesh",
    name: "ET Now Swadesh",
    quality: "720p",
    url: "https://d32gxr3r1ksq2p.cloudfront.net/master.m3u8",
    status: "loading",
    isLive: false,
    viewers: "456K",
    uptime: "24/7",
    category: "National",
    type: "hls", // hls or embed
  },
  {
    id: "india-today",
    name: "India Today",
    quality: "720p",
    url: "https://indiatodaylive.akamaized.net/hls/live/2014320/indiatoday/indiatodaylive/playlist.m3u8",
    status: "loading",
    isLive: false,
    viewers: "1.6M",
    uptime: "16/7",
    category: "National",
    type: "hls", // hls or embed
  },

  {
    id: "lok-sabha-tv",
    name: "Lok Sabha TV",
    quality: "1080p",
    url: "https://playhls.media.nic.in/hls/live/lstv/lstv.m3u8",
    status: "loading",
    isLive: false,
    viewers: "678K",
    uptime: "24/7",
    category: "National",
    type: "hls", // hls or embed
  },
  {
    id: "ndtv-24x7",
    name: "NDTV 24x7",
    quality: "480p",
    url: "https://ndtv24x7elemarchana.akamaized.net/hls/live/2003678/ndtv24x7/master.m3u8",
    status: "loading",
    isLive: false,
    viewers: "1.1M",
    uptime: "24/7",
    category: "National",
    type: "hls", // hls or embed
  },
  {
    id: "ndtv-india",
    name: "NDTV India",
    quality: "480p",
    url: "https://ndtvindiaelemarchana.akamaized.net/hls/live/2003679/ndtvindia/master.m3u8",
    status: "loading",
    isLive: false,
    viewers: "934K",
    uptime: "24/7",
    category: "National",
    type: "hls", // hls or embed
  },
  {
    id: "news24",
    name: "News 24",
    quality: "720p",
    url: "https://vidcdn.vidgyor.com/news24-origin/liveabr/playlist.m3u8",
    status: "loading",
    isLive: false,
    viewers: "756K",
    uptime: "24/7",
    category: "National",
    type: "hls", // hls or embed
  },
  {
    id: "republic-bharat",
    name: "Republic Bharat",
    quality: "1080p",
    url: "https://vg-republictvlive.akamaized.net/v1/master/611d79b11b77e2f571934fd80ca1413453772ac7/vglive-sk-275673/main.m3u8",
    status: "loading",
    isLive: false,
    viewers: "2.1M",
    uptime: "24/7",
    category: "National",
    type: "hls", // hls or embed
  },

  {
    id: "tv9-bharatvarsh",
    name: "TV9 Bharatvarsh",
    quality: "720p",
    url: "https://dyjmyiv3bp2ez.cloudfront.net/pub-iotv9hinjzgtpe/liveabr/playlist.m3u8",
    status: "loading",
    isLive: false,
    viewers: "834K",
    uptime: "24/7",
    category: "National",
    type: "hls", // hls or embed
  },
  {
    id: "wion",
    name: "WION",
    quality: "1080p",
    url: "https://d7x8z4yuq42qn.cloudfront.net/index_7.m3u8",
    status: "loading",
    isLive: false,
    viewers: "567K",
    uptime: "24/7",
    category: "National",
    type: "hls", // hls or embed
  },

  {
    id: "dd-uttar-pradesh",
    name: "DD Uttar Pradesh",
    quality: "720p",
    url: "https://cdn-1.pishow.tv/live/36/master.m3u8",
    status: "loading",
    isLive: false,
    viewers: "312K",
    uptime: "24/7",
    category: "UP Regional",
    type: "hls", // hls or embed
  },
  {
    id: "india-tv-embed",
    name: "India TV",
    quality: "HD",
    url: "https://www.yupptv.com/yupptvnew/channels/indiatv/live/embed",
    type: "embed",
    status: "loading",
    isLive: false,
    viewers: "1.9M",
    uptime: "24/7",
    category: "National",
  },
  {
    id: "abp-news-embed",
    name: "ABP News",
    quality: "HD",
    url: "https://www.yupptv.com/yupptvnew/channels/abp-news/live/embed",
    type: "embed",
    status: "loading",
    isLive: false,
    viewers: "1.5M",
    uptime: "24/7",
    category: "National",
  },
  {
    id: "zee-news-embed",
    name: "Zee News",
    quality: "HD",
    url: "https://www.yupptv.com/yupptvnew/channels/zee-news/live/embed",
    type: "embed",
    status: "loading",
    isLive: false,
    viewers: "1.4M",
    uptime: "24/7",
    category: "National",
  },
  {
    id: "first-india-news",
    name: "First India News",
    quality: "1080p",
    url: "https://xlbor37ydvaj-hls-live.wmncdn.net/firstindianewstv1/live.stream/index.m3u8",
    type: "hls",
    status: "loading",
    isLive: false,
    viewers: "2.1M",
    uptime: "24/7",
    category: "National",
  },
  {
    id: "ndtv-247",
    name: "NDTV 24/7",
    quality: "1080p",
    url: "https://ndtv24x7elemarchana.akamaized.net/hls/live/2003678/ndtv24x7/master.m3u8",
    type: "hls",
    status: "loading",
    isLive: false,
    viewers: "2.1M",
    uptime: "24/7",
    category: "National",
  },
  {
    id: "news-24",
    name: "News 24",
    quality: "1080p",
    url: "https://vidcdn.vidgyor.com/news24-origin/liveabr/playlist.m3u8",
    type: "hls",
    status: "loading",
    isLive: false,
    viewers: "2.1M",
    uptime: "24/7",
    category: "National",
  },
];
export  {channels};
